### ISSUE TITLE
Raise input key presses logging to a higher verbosity

### ISSUE THREAD

**Issue by TheEngineerGuy** [jsiegenthaler/homebridge-samsungtvht#10]
Loving the plugin so far. Thank you for updating the ping Log level.

Similarly, every key press is being logged in normal logging mode (volume up/down, input, etc.). Can we bump this logging for higher verbosity please?

**Comment by jsiegenthaler** [comment]
Thanks for your feedback.
I'll look at this in a week or so as I'm busy for a bit. 
I primarily logged all the key presses to confirm that everything was working fine, so in other words: for my own use. But now that the plugin has proven itself as being reliable and stable, I guess it's good to bump the key presses up a log level.

**Comment by jsiegenthaler** [comment]
PS: keep up the feedback. All feedback is good feedback.

**Comment by TheEngineerGuy** [comment]
Thank you very much for looking into this. Love the work you have put in.

**Comment by jsiegenthaler** [comment]
Hi @TheEngineerGuy 
I've released an  beta version which shifts the sendKey messages up to debugLevel > 0
Please try it out and let me know if it covers what you want.
You can install the beta version from Homebridge: Plugin Tools menu > Install Alternate Version

**Comment by TheEngineerGuy** [comment]
Thank you @jsiegenthaler . Confirmed, no more log entries for key presses are being created at normal logging level.
