### ISSUE TITLE
KEY_VOLUP error Samsung Remote Client: Device is off or unreachable

### ISSUE THREAD

**Issue by Floppotron** [jsiegenthaler/homebridge-samsungtvht#14]
Hello @all,

I'm using a 2014 Samsung UE48H6870.
I decided to integrate it into my HomeKit-System, which did work in general. (Should work, regarding your description)
The power state is being displayed correctly, but I'm unable to control my TV via HomeKit or the control center remote on my iOS devices. When sending any command i get the error message KEY_VOLUP error Samsung Remote Client: Device is off or unreachable.
It's not off nor unreachable since the ping command seems to work correctly
Did I miss a step?

**Comment by jsiegenthaler** [comment]
You TV is an H-Series from 2014. I believe the H-Series use the Tizen operating system. This plugin is for the earlier generation, non-Tizen TVs, and thus cannot work with your TV.

From the Readme Requirements:
https://github.com/jsiegenthaler/homebridge-samsungtvht#requirements

An Orsay (non-Tizen) Samsung TV or Home Theater system from C-series (2010), D-series (2011), E-series (2012), F-series (2013) models. Orsay started in 2011, Tizen started in 2015, so TVs and HTs from 2011 to 2015 generally work with this plugin. May also work on some later models as well.

**Comment by jsiegenthaler** [comment]
Closing the issue as the H-Series TV is not supported by this plugin
