### ISSUE TITLE
cec-client not found

### ISSUE THREAD

**Issue by Weezys9919** [jsiegenthaler/homebridge-samsungtvht#16]
Everything work eccept cec command. When i put power on command : 

echo 'on 5' | cec-client -s -d 1

When i click on my HT to power on i get an error back :

setPower: powerOnCommand: echo 'on 5' | cec-client -s -d 1
setPower: powerOnCommand: /bin/sh: 1: cec-client: not found

*Last version*

**Comment by jsiegenthaler** [comment]
You need to install the CEC-client separately. Get it here:
https://github.com/Pulse-Eight/libcec

Good instructions here:
https://gist.github.com/rmtsrc/dc35cd1458cd995631a4f041ab11ff74

**Comment by jsiegenthaler** [comment]
Closing issue as CEC needs to be installed by user
