### ISSUE TITLE
TV not showing in HomeKit

### ISSUE THREAD

**Issue by Mikkowoehrl** [jsiegenthaler/homebridge-samsungtvht#17]
Grüezi / Hello,
i have been using the plugin for a few months now, but somehow it no longer works. I am still able to control the TV via the device view in Homebridge, but no longer via HomeKit. I have deleted and reconfigured the plugin several times, but the problem remains. I have also tried adding the TV to HomeKit via a sub-bridge, but I can only add the bridge, not the TV. Is there something i did wrong or do i nee to change something? Thanks in advance

**Comment by jsiegenthaler** [comment]
Try removing / resetting the tv device in Homebridge

**Comment by jsiegenthaler** [comment]
Closing issue as no feedback heard from user

**Comment by krebbi** [comment]
Have the same problem. already removed and added the plugin in HB without any luck. 
Probably not compatible with HB2 ?
