### ISSUE TITLE
Support for HT-H6550WM

### ISSUE THREAD

**Issue by Faisalthe01** [jsiegenthaler/homebridge-samsungtvht#20]
Hi,

how to find out if my Samsung HT-H6550WM Blu Ray player is supported with this plugin?

**Comment by jsiegenthaler** [comment]
i googled your model number and found out:
1. It is an H-series (first character)
2. It is from around 2014
Both these facts suggest it would not work. But the best way to determine that is just to install the plugin and try it.

**Comment by jsiegenthaler** [comment]
Closing as no feedback received
