### ISSUE TITLE
Control Center Remote Volume not working anymore

### ISSUE THREAD

**Issue by Mikkowoehrl** [jsiegenthaler/homebridge-samsungtvht#22]
**Describe Your Problem:**
Since a while the volume control doesn’t work anymore when using the remote in control center. All buttons still work, besides volume control

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by jsiegenthaler** [comment]
Reboot your home hub. Apple Home gets confused sometimes. 

Check your logs. Is the command being sent? Is the IP address right?

**Comment by Mikkowoehrl** [comment]
Yeah i have already tried that but it didnt change anything. I also checked the logs but no command is being send when i press the buttons. It just changes the volume of my phone and doesnt even show the Animation that it used to show where the button that was pressed showed up on the side of the screen. IP Adress is correct because as i said all Buttons like Up and Down work normaly, besides the volume.

**Comment by jsiegenthaler** [comment]
That's an Apple HomeKit Remote Control issue. I've had it happen to me. The best solution was to reboot the iPhone and the Home Hub. Then wait for the accessories to be detected properly. Once the app properly detects the TV accessory as a TV it then enables the volume control buttons.

**Comment by Mikkowoehrl** [comment]
I just tried what you suggested, I unplugged my Apple TV and my HomePod mini waited a few minutes, then plugged them both back in and restarted my Phone and even HomeBridge but it’s still not working. The only thing I could think of that could have caused this problem is that I’m also running HomeAssistant with wich the TV is also connected. Could that be a problem or should they both just work fine and it’s something different?

**Comment by jsiegenthaler** [comment]
This is purely an issue with the Apple Remote Control app getting confused. 

The plugin has no control whatsoever about display of the Remote Control on the iPhone. That's handled by the iPhone. 

I'll check mine when I get home later today.

**Comment by Mikkowoehrl** [comment]
Ok that’s weird. It also happens on my iPad so it’s not iPhone exclusive I guess

**Comment by jsiegenthaler** [comment]
Hi. sorry but this is very much an iOS thing, the plugin has no impact on the Apple Remote Control display or on the keypresses sent by the Remote Control. Nothing I can do. So I'm closing this issue
