### ISSUE TITLE
Add support for H-series 2014 TVs

### ISSUE THREAD

**Issue by jsiegenthaler** [jsiegenthaler/homebridge-samsungtvht#3]
H-Series from 2014 require a PIN to authenticate the remote with the TV, which is not supported by this plugin.

See here for reference info:
https://imkapps.com/mytifi/manual/#Use_with_H-Series_or_J-Series

The plugin needs to be adapted to support authentication for the H-Series

See issue https://github.com/jsiegenthaler/homebridge-samsungtvht/issues/2 where the issue of connecting to an H-series was discovered

**Comment by ChrisTav424** [comment]
Thanks @jsiegenthaler this is great! 

Happy to help in any way I can :)

**Comment by jsiegenthaler** [comment]
@ChrisTav424 
What's your skillset? Are you familiar with coding javascript?

To support the H-series I have to move to a different node module for the remote control, and as I do not have a H-series TV myself, makes it very difficult for me to test it.

One of the easiest ways to find what works is for you to try various other Samsung Homebridge plugins until you find one that works, and then let me know which one it is. I can then research that plugin and see how the PIN code and encryption is handled.

**Comment by ChrisTav424** [comment]
Thanks @jsiegenthaler, I tried using the myTiFi app this week and it doesn't work so I think this is a non starter for my TV, but I do want to say thank you so much for all your help :)

**Comment by jsiegenthaler** [comment]
OK. if myTifi doesn't work, then there's no way I can get it to work.

I'll close this issue
