### ISSUE TITLE
Ping response keeps flooding the logs

### ISSUE THREAD

**Issue by TheEngineerGuy** [jsiegenthaler/homebridge-samsungtvht#8]
When there is a non-zero packet loss, (75%, 50% or 66.6667%) ping keeps on flooding the HB logs. So, for 90% of the day when TV is off, this plugin keeps on filling up logs with pointless info. Personally, I would rather have this level of logging in a higher verbosity, not at default level of 0.

For now uninstalling the plugin. Let me know if and when you wish for me to test a newer version.

**Comment by jsiegenthaler** [comment]
Good point. I’ll look in to this in a few weeks when I’m back home. 

Regards Jochen

**Comment by jsiegenthaler** [comment]
Fixed in v0.1.19

**Comment by TheEngineerGuy** [comment]
Thank you! Testing it.
